server:
  port: 8081
spring:
  application:
    name: client-producer
eureka:
  instance:
    #是否使用IP地址进行访问
    prefer-ip-address: true
    #实例显示名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project:version@
  client:
    # 注册到Eureka服务端的地址,集群用逗号分隔
    service-url:
      defaultZone: http://localhost:8761/eureka/